Fixes #245: Fixes loading of resources when used from other modules
SonarSource/sonar-analyzer-commons pull request #247
Opened 2022-08-04 15:03 UTC by Wohops

2022-08-04 15:04 UTC, Wohops commented
Deprecates #246 . Much simpler solution.

2022-08-04 15:04 UTC, Wohops commented
Required by https://github.com/SonarSource/sonar-java/pull/4144

2022-08-04 15:47 UTC, alban-auzeill requested changes

2022-08-04 15:47 UTC, alban-auzeill commented on pom.xml
> +    <maven.compiler.release>11</maven.compiler.release>
⚠️  This change is not required and will impact: sonar-css, sonar-flex, sonar-rpg, sonar-xml, sonar-pli, sonar-vb, sonar-tsql, sonar-plsql, sonar-abap, sonar-cobol
Why?

2022-08-05 08:04 UTC, alban-auzeill approved these changes

2022-08-05 08:04 UTC, merged